package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAutorizacionCrear calls the stored procedure 'CaresoftDB.spAutorizacionCrear(int, decimal, varchar, int, varchar, varchar, int)' on db.
func SpAutorizacionCrear(ctx context.Context, db DB, pIDAseguradora uint, pMontoAsegurado float64, pFacturaCodigo string, pIDIngreso uint, pConsultaCodigo, pServicioCodigo string, pIDProducto uint) error {
	// call CaresoftDB.spAutorizacionCrear
	const sqlstr = `CALL CaresoftDB.spAutorizacionCrear(?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAseguradora, pMontoAsegurado, pFacturaCodigo, pIDIngreso, pConsultaCodigo, pServicioCodigo, pIDProducto); err != nil {
		return logerror(err)
	}
	return nil
}
