package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProductoListar calls the stored procedure 'CaresoftDB.spProductoListar(decimal)' on db.
func SpProductoListar(ctx context.Context, db DB, pCosto float64) error {
	// call CaresoftDB.spProductoListar
	const sqlstr = `CALL CaresoftDB.spProductoListar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pCosto); err != nil {
		return logerror(err)
	}
	return nil
}
