package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpTipoServicioEliminar calls the stored procedure 'CaresoftDB.spTipoServicioEliminar(int)' on db.
func SpTipoServicioEliminar(ctx context.Context, db DB, pIDTipoServicio uint) error {
	// call CaresoftDB.spTipoServicioEliminar
	const sqlstr = `CALL CaresoftDB.spTipoServicioEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDTipoServicio); err != nil {
		return logerror(err)
	}
	return nil
}
