package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpUsuarioListar calls the stored procedure 'CaresoftDB.spUsuarioListar(varchar, enum('m','f'), date, enum('p','a','m','e','c'))' on db.
func SpUsuarioListar(ctx context.Context, db DB, pDocumento string, pGenero EnumMF, pFechaNacimiento time.Time, pRol EnumPAMEC) error {
	// call CaresoftDB.spUsuarioListar
	const sqlstr = `CALL CaresoftDB.spUsuarioListar(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumento, pGenero, pFechaNacimiento, pRol); err != nil {
		return logerror(err)
	}
	return nil
}
