package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpServicioEliminar calls the stored procedure 'CaresoftDB.spServicioEliminar(varchar)' on db.
func SpServicioEliminar(ctx context.Context, db DB, pServicioCodigo string) error {
	// call CaresoftDB.spServicioEliminar
	const sqlstr = `CALL CaresoftDB.spServicioEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pServicioCodigo); err != nil {
		return logerror(err)
	}
	return nil
}
