package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpServicioActualizar calls the stored procedure 'CaresoftDB.spServicioActualizar(varchar, int, varchar, varchar, decimal)' on db.
func SpServicioActualizar(ctx context.Context, db DB, pServicioCodigo string, pIDTipoServicio uint, pNombre, pDescripcion string, pCosto float64) error {
	// call CaresoftDB.spServicioActualizar
	const sqlstr = `CALL CaresoftDB.spServicioActualizar(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pServicioCodigo, pIDTipoServicio, pNombre, pDescripcion, pCosto); err != nil {
		return logerror(err)
	}
	return nil
}
