package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpServicioListar calls the stored procedure 'CaresoftDB.spServicioListar()' on db.
func SpServicioListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spServicioListar
	const sqlstr = `CALL CaresoftDB.spServicioListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
