package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSucursalActualizar calls the stored procedure 'CaresoftDB.spSucursalActualizar(int, varchar, varchar, varchar)' on db.
func SpSucursalActualizar(ctx context.Context, db DB, pIDSucursal uint, pNombre, pDireccion, pTelefono string) error {
	// call CaresoftDB.spSucursalActualizar
	const sqlstr = `CALL CaresoftDB.spSucursalActualizar(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDSucursal, pNombre, pDireccion, pTelefono); err != nil {
		return logerror(err)
	}
	return nil
}
