package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSucursalCrear calls the stored procedure 'CaresoftDB.spSucursalCrear(varchar, varchar, varchar)' on db.
func SpSucursalCrear(ctx context.Context, db DB, pNombre, pDireccion, pTelefono string) error {
	// call CaresoftDB.spSucursalCrear
	const sqlstr = `CALL CaresoftDB.spSucursalCrear(?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNombre, pDireccion, pTelefono); err != nil {
		return logerror(err)
	}
	return nil
}
