package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpMetodoPagoListar calls the stored procedure 'CaresoftDB.spMetodoPagoListar()' on db.
func SpMetodoPagoListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spMetodoPagoListar
	const sqlstr = `CALL CaresoftDB.spMetodoPagoListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
