package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpTipoServicioActualizar calls the stored procedure 'CaresoftDB.spTipoServicioActualizar(int, varchar)' on db.
func SpTipoServicioActualizar(ctx context.Context, db DB, pIDTipoServicio uint, pNuevoNombre string) error {
	// call CaresoftDB.spTipoServicioActualizar
	const sqlstr = `CALL CaresoftDB.spTipoServicioActualizar(?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDTipoServicio, pNuevoNombre); err != nil {
		return logerror(err)
	}
	return nil
}
