package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAseguradoraCrear calls the stored procedure 'CaresoftDB.spAseguradoraCrear(varchar, varchar, varchar, varchar)' on db.
func SpAseguradoraCrear(ctx context.Context, db DB, pNombre, pDireccion, pTelefono, pCorreo string) error {
	// call CaresoftDB.spAseguradoraCrear
	const sqlstr = `CALL CaresoftDB.spAseguradoraCrear(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNombre, pDireccion, pTelefono, pCorreo); err != nil {
		return logerror(err)
	}
	return nil
}
