package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAutorizacionEliminar calls the stored procedure 'CaresoftDB.spAutorizacionEliminar(int)' on db.
func SpAutorizacionEliminar(ctx context.Context, db DB, pIDAutorizacion uint) error {
	// call CaresoftDB.spAutorizacionEliminar
	const sqlstr = `CALL CaresoftDB.spAutorizacionEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAutorizacion); err != nil {
		return logerror(err)
	}
	return nil
}
