package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpConsultaPrescribirProducto calls the stored procedure 'CaresoftDB.spConsultaPrescribirProducto(varchar, int, int)' on db.
func SpConsultaPrescribirProducto(ctx context.Context, db DB, pConsultaCodigo string, pIDProducto uint, pCantidad int) error {
	// call CaresoftDB.spConsultaPrescribirProducto
	const sqlstr = `CALL CaresoftDB.spConsultaPrescribirProducto(?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pConsultaCodigo, pIDProducto, pCantidad); err != nil {
		return logerror(err)
	}
	return nil
}
