package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSalaEliminar calls the stored procedure 'CaresoftDB.spSalaEliminar(int)' on db.
func SpSalaEliminar(ctx context.Context, db DB, pNumSala uint) error {
	// call CaresoftDB.spSalaEliminar
	const sqlstr = `CALL CaresoftDB.spSalaEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNumSala); err != nil {
		return logerror(err)
	}
	return nil
}
