package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpConsultasListar calls the stored procedure 'CaresoftDB.spConsultasListar(varchar, varchar, datetime, datetime)' on db.
func SpConsultasListar(ctx context.Context, db DB, pDocumentoPaciente, pDocumentoMedico string, pFechaInicio, pFechaFin time.Time) error {
	// call CaresoftDB.spConsultasListar
	const sqlstr = `CALL CaresoftDB.spConsultasListar(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoPaciente, pDocumentoMedico, pFechaInicio, pFechaFin); err != nil {
		return logerror(err)
	}
	return nil
}
