package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProductoActualizar calls the stored procedure 'CaresoftDB.spProductoActualizar(int, varchar, varchar, decimal, int)' on db.
func SpProductoActualizar(ctx context.Context, db DB, pIDProducto uint, pNombre, pDescripcion string, pCosto float64, pLoteDisponible uint) error {
	// call CaresoftDB.spProductoActualizar
	const sqlstr = `CALL CaresoftDB.spProductoActualizar(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDProducto, pNombre, pDescripcion, pCosto, pLoteDisponible); err != nil {
		return logerror(err)
	}
	return nil
}
