package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAseguradoraListar calls the stored procedure 'CaresoftDB.spAseguradoraListar(int, varchar, varchar, varchar)' on db.
func SpAseguradoraListar(ctx context.Context, db DB, pIDAseguradora uint, pNombre, pTelefono, pCorreo string) error {
	// call CaresoftDB.spAseguradoraListar
	const sqlstr = `CALL CaresoftDB.spAseguradoraListar(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAseguradora, pNombre, pTelefono, pCorreo); err != nil {
		return logerror(err)
	}
	return nil
}
