package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAseguradoraActualizar calls the stored procedure 'CaresoftDB.spAseguradoraActualizar(int, varchar, varchar, varchar, varchar)' on db.
func SpAseguradoraActualizar(ctx context.Context, db DB, pIDAseguradora uint, pNombre, pDireccion, pTelefono, pCorreo string) error {
	// call CaresoftDB.spAseguradoraActualizar
	const sqlstr = `CALL CaresoftDB.spAseguradoraActualizar(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAseguradora, pNombre, pDireccion, pTelefono, pCorreo); err != nil {
		return logerror(err)
	}
	return nil
}
