package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpIngresoRelacionarAfeccion calls the stored procedure 'CaresoftDB.spIngresoRelacionarAfeccion(int, int)' on db.
func SpIngresoRelacionarAfeccion(ctx context.Context, db DB, pIDIngreso, pIDAfeccion uint) error {
	// call CaresoftDB.spIngresoRelacionarAfeccion
	const sqlstr = `CALL CaresoftDB.spIngresoRelacionarAfeccion(?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDIngreso, pIDAfeccion); err != nil {
		return logerror(err)
	}
	return nil
}
