package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaCrear calls the stored procedure 'CaresoftDB.spFacturaCrear(varchar, int, int, varchar)' on db.
func SpFacturaCrear(ctx context.Context, db DB, pFacturaCodigo string, pIDCuenta, pIDSucursal uint, pDocumentoCajero string) error {
	// call CaresoftDB.spFacturaCrear
	const sqlstr = `CALL CaresoftDB.spFacturaCrear(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pIDCuenta, pIDSucursal, pDocumentoCajero); err != nil {
		return logerror(err)
	}
	return nil
}
