package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpFacturaListar calls the stored procedure 'CaresoftDB.spFacturaListar(varchar, datetime, datetime)' on db.
func SpFacturaListar(ctx context.Context, db DB, pDocumentoCajero string, pFechaInicio, pFechaFin time.Time) error {
	// call CaresoftDB.spFacturaListar
	const sqlstr = `CALL CaresoftDB.spFacturaListar(?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoCajero, pFechaInicio, pFechaFin); err != nil {
		return logerror(err)
	}
	return nil
}
