package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaRelacionarServicio calls the stored procedure 'CaresoftDB.spFacturaRelacionarServicio(varchar, varchar, text, decimal)' on db.
func SpFacturaRelacionarServicio(ctx context.Context, db DB, pFacturaCodigo, pServicioCodigo, pResultados string, pCosto float64) error {
	// call CaresoftDB.spFacturaRelacionarServicio
	const sqlstr = `CALL CaresoftDB.spFacturaRelacionarServicio(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pServicioCodigo, pResultados, pCosto); err != nil {
		return logerror(err)
	}
	return nil
}
