package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpPagoListar calls the stored procedure 'CaresoftDB.spPagoListar()' on db.
func SpPagoListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spPagoListar
	const sqlstr = `CALL CaresoftDB.spPagoListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
