package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpMetodoPagoEliminar calls the stored procedure 'CaresoftDB.spMetodoPagoEliminar(int)' on db.
func SpMetodoPagoEliminar(ctx context.Context, db DB, pIDMetodoPago uint) error {
	// call CaresoftDB.spMetodoPagoEliminar
	const sqlstr = `CALL CaresoftDB.spMetodoPagoEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDMetodoPago); err != nil {
		return logerror(err)
	}
	return nil
}
