package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpConsultaActualizar calls the stored procedure 'CaresoftDB.spConsultaActualizar(varchar, varchar, varchar, int, varchar, text, decimal)' on db.
func SpConsultaActualizar(ctx context.Context, db DB, pConsultaCodigo, pDocumentoPaciente, pDocumentoMedico string, pIDConsultorio uint, pMotivo, pComentarios string, pCosto float64) error {
	// call CaresoftDB.spConsultaActualizar
	const sqlstr = `CALL CaresoftDB.spConsultaActualizar(?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pConsultaCodigo, pDocumentoPaciente, pDocumentoMedico, pIDConsultorio, pMotivo, pComentarios, pCosto); err != nil {
		return logerror(err)
	}
	return nil
}
