package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSucursalListar calls the stored procedure 'CaresoftDB.spSucursalListar()' on db.
func SpSucursalListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spSucursalListar
	const sqlstr = `CALL CaresoftDB.spSucursalListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
