package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpIngresoActualizar calls the stored procedure 'CaresoftDB.spIngresoActualizar(int, varchar, varchar, varchar, varchar, int, int, decimal, datetime)' on db.
func SpIngresoActualizar(ctx context.Context, db DB, pIDIngreso uint, pDocumentoPaciente, pDocumentoEnfermero, pDocumentoMedico, pConsultaCodigo string, pIDAutorizacion, pNumSala uint, pCostoEstancia float64, pFechaAlta time.Time) error {
	// call CaresoftDB.spIngresoActualizar
	const sqlstr = `CALL CaresoftDB.spIngresoActualizar(?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDIngreso, pDocumentoPaciente, pDocumentoEnfermero, pDocumentoMedico, pConsultaCodigo, pIDAutorizacion, pNumSala, pCostoEstancia, pFechaAlta); err != nil {
		return logerror(err)
	}
	return nil
}
