package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpMetodoPagoCrear calls the stored procedure 'CaresoftDB.spMetodoPagoCrear(varchar)' on db.
func SpMetodoPagoCrear(ctx context.Context, db DB, pNombre string) error {
	// call CaresoftDB.spMetodoPagoCrear
	const sqlstr = `CALL CaresoftDB.spMetodoPagoCrear(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNombre); err != nil {
		return logerror(err)
	}
	return nil
}
