package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpUsuarioEliminar calls the stored procedure 'CaresoftDB.spUsuarioEliminar(varchar)' on db.
func SpUsuarioEliminar(ctx context.Context, db DB, pDocumentoOUsuarioCodigo string) error {
	// call CaresoftDB.spUsuarioEliminar
	const sqlstr = `CALL CaresoftDB.spUsuarioEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoOUsuarioCodigo); err != nil {
		return logerror(err)
	}
	return nil
}
