package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpIngresoListar calls the stored procedure 'CaresoftDB.spIngresoListar(varchar, varchar, varchar, varchar, int, int, decimal, datetime, datetime)' on db.
func SpIngresoListar(ctx context.Context, db DB, pDocumentoPaciente, pDocumentoEnfermero, pDocumentoMedico, pConsultaCodigo string, pIDAutorizacion, pNumSala uint, pCostoEstancia float64, pFechaIngreso, pFechaAlta time.Time) error {
	// call CaresoftDB.spIngresoListar
	const sqlstr = `CALL CaresoftDB.spIngresoListar(?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoPaciente, pDocumentoEnfermero, pDocumentoMedico, pConsultaCodigo, pIDAutorizacion, pNumSala, pCostoEstancia, pFechaIngreso, pFechaAlta); err != nil {
		return logerror(err)
	}
	return nil
}
