package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaCrearConsulta calls the stored procedure 'CaresoftDB.spFacturaCrearConsulta(varchar, int, varchar, int, varchar)' on db.
func SpFacturaCrearConsulta(ctx context.Context, db DB, pFacturaCodigo string, pIDCuenta uint, pConsultaCodigo string, pIDSucursal uint, pDocumentoCajero string) error {
	// call CaresoftDB.spFacturaCrearConsulta
	const sqlstr = `CALL CaresoftDB.spFacturaCrearConsulta(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pIDCuenta, pConsultaCodigo, pIDSucursal, pDocumentoCajero); err != nil {
		return logerror(err)
	}
	return nil
}
