package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProveedorListar calls the stored procedure 'CaresoftDB.spProveedorListar()' on db.
func SpProveedorListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spProveedorListar
	const sqlstr = `CALL CaresoftDB.spProveedorListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
