package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpUsuarioCrearPersonalMedico calls the stored procedure 'CaresoftDB.spUsuarioCrearPersonalMedico(varchar, enum('i','p'), int, varchar, varchar, enum('m','f'), date, varchar, varchar, varchar, enum('m','e'), varchar, varchar)' on db.
func SpUsuarioCrearPersonalMedico(ctx context.Context, db DB, pDocumento string, pTipoDocumento EnumIP, pNumLicenciaMedica uint, pNombre, pApellido string, pGenero EnumMF, pFechaNacimiento time.Time, pTelefono, pCorreo, pDireccion string, pRol EnumME, pUsuarioCodigo, pUsuarioContra string) error {
	// call CaresoftDB.spUsuarioCrearPersonalMedico
	const sqlstr = `CALL CaresoftDB.spUsuarioCrearPersonalMedico(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumento, pTipoDocumento, pNumLicenciaMedica, pNombre, pApellido, pGenero, pFechaNacimiento, pTelefono, pCorreo, pDireccion, pRol, pUsuarioCodigo, pUsuarioContra); err != nil {
		return logerror(err)
	}
	return nil
}
