package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaRelacionarProducto calls the stored procedure 'CaresoftDB.spFacturaRelacionarProducto(varchar, int, text, decimal)' on db.
func SpFacturaRelacionarProducto(ctx context.Context, db DB, pFacturaCodigo string, pIDProducto uint, pResultados string, pCosto float64) error {
	// call CaresoftDB.spFacturaRelacionarProducto
	const sqlstr = `CALL CaresoftDB.spFacturaRelacionarProducto(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pIDProducto, pResultados, pCosto); err != nil {
		return logerror(err)
	}
	return nil
}
