package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpPagoActualizar calls the stored procedure 'CaresoftDB.spPagoActualizar(int, int, decimal)' on db.
func SpPagoActualizar(ctx context.Context, db DB, pIDPago, pIDCuenta uint, pMontoPagado float64) error {
	// call CaresoftDB.spPagoActualizar
	const sqlstr = `CALL CaresoftDB.spPagoActualizar(?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDPago, pIDCuenta, pMontoPagado); err != nil {
		return logerror(err)
	}
	return nil
}
