package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpPagoEliminar calls the stored procedure 'CaresoftDB.spPagoEliminar(int)' on db.
func SpPagoEliminar(ctx context.Context, db DB, pIDPago uint) error {
	// call CaresoftDB.spPagoEliminar
	const sqlstr = `CALL CaresoftDB.spPagoEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDPago); err != nil {
		return logerror(err)
	}
	return nil
}
