package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProductoRelacionarProveedor calls the stored procedure 'CaresoftDB.spProductoRelacionarProveedor(int, int)' on db.
func SpProductoRelacionarProveedor(ctx context.Context, db DB, pIDProducto, pRncProveedor uint) error {
	// call CaresoftDB.spProductoRelacionarProveedor
	const sqlstr = `CALL CaresoftDB.spProductoRelacionarProveedor(?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDProducto, pRncProveedor); err != nil {
		return logerror(err)
	}
	return nil
}
