package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSalaToggleEstado calls the stored procedure 'CaresoftDB.spSalaToggleEstado(int)' on db.
func SpSalaToggleEstado(ctx context.Context, db DB, pNumSala uint) error {
	// call CaresoftDB.spSalaToggleEstado
	const sqlstr = `CALL CaresoftDB.spSalaToggleEstado(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNumSala); err != nil {
		return logerror(err)
	}
	return nil
}
