package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpReservaListar calls the stored procedure 'CaresoftDB.spReservaListar(varchar, varchar, varchar, datetime, enum('p','r'))' on db.
func SpReservaListar(ctx context.Context, db DB, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo string, pFechaReserva time.Time, pEstado EnumPR) error {
	// call CaresoftDB.spReservaListar
	const sqlstr = `CALL CaresoftDB.spReservaListar(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo, pFechaReserva, pEstado); err != nil {
		return logerror(err)
	}
	return nil
}
