package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaCrearIngreso calls the stored procedure 'CaresoftDB.spFacturaCrearIngreso(varchar, int, int, int, varchar)' on db.
func SpFacturaCrearIngreso(ctx context.Context, db DB, pFacturaCodigo string, pIDCuenta, pIDIngreso, pIDSucursal uint, pDocumentoCajero string) error {
	// call CaresoftDB.spFacturaCrearIngreso
	const sqlstr = `CALL CaresoftDB.spFacturaCrearIngreso(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pIDCuenta, pIDIngreso, pIDSucursal, pDocumentoCajero); err != nil {
		return logerror(err)
	}
	return nil
}
