package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpUsuarioActualizarDatos calls the stored procedure 'CaresoftDB.spUsuarioActualizarDatos(varchar, enum('i','p'), varchar, varchar, enum('m','f'), date, varchar, varchar, varchar)' on db.
func SpUsuarioActualizarDatos(ctx context.Context, db DB, pDocumento string, pTipoDocumento EnumIP, pNombre, pApellido string, pGenero EnumMF, pFechaNacimiento time.Time, pTelefono, pCorreo, pDireccion string) error {
	// call CaresoftDB.spUsuarioActualizarDatos
	const sqlstr = `CALL CaresoftDB.spUsuarioActualizarDatos(?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumento, pTipoDocumento, pNombre, pApellido, pGenero, pFechaNacimiento, pTelefono, pCorreo, pDireccion); err != nil {
		return logerror(err)
	}
	return nil
}
