package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpReservaActualizar calls the stored procedure 'CaresoftDB.spReservaActualizar(int, varchar, varchar, varchar, datetime)' on db.
func SpReservaActualizar(ctx context.Context, db DB, pIDReserva uint, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo string, pFechaReserva time.Time) error {
	// call CaresoftDB.spReservaActualizar
	const sqlstr = `CALL CaresoftDB.spReservaActualizar(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDReserva, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo, pFechaReserva); err != nil {
		return logerror(err)
	}
	return nil
}
