package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaActualizar calls the stored procedure 'CaresoftDB.spFacturaActualizar(varchar, int, varchar, int, int, varchar, decimal, decimal)' on db.
func SpFacturaActualizar(ctx context.Context, db DB, pFacturaCodigo string, pIDCuenta uint, pConsultaCodigo string, pIDIngreso, pIDSucursal uint, pDocumentoCajero string, pMontoSubtotal, pMontoTotal float64) error {
	// call CaresoftDB.spFacturaActualizar
	const sqlstr = `CALL CaresoftDB.spFacturaActualizar(?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo, pIDCuenta, pConsultaCodigo, pIDIngreso, pIDSucursal, pDocumentoCajero, pMontoSubtotal, pMontoTotal); err != nil {
		return logerror(err)
	}
	return nil
}
