package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpReservaCrear calls the stored procedure 'CaresoftDB.spReservaCrear(varchar, varchar, varchar, datetime)' on db.
func SpReservaCrear(ctx context.Context, db DB, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo string, pFechaReserva time.Time) error {
	// call CaresoftDB.spReservaCrear
	const sqlstr = `CALL CaresoftDB.spReservaCrear(?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumentoPaciente, pDocumentoMedico, pServicioCodigo, pFechaReserva); err != nil {
		return logerror(err)
	}
	return nil
}
