package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProveedorEliminar calls the stored procedure 'CaresoftDB.spProveedorEliminar(int)' on db.
func SpProveedorEliminar(ctx context.Context, db DB, pRncProveedor uint) error {
	// call CaresoftDB.spProveedorEliminar
	const sqlstr = `CALL CaresoftDB.spProveedorEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pRncProveedor); err != nil {
		return logerror(err)
	}
	return nil
}
