package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSucursalEliminar calls the stored procedure 'CaresoftDB.spSucursalEliminar(int)' on db.
func SpSucursalEliminar(ctx context.Context, db DB, pIDSucursal uint) error {
	// call CaresoftDB.spSucursalEliminar
	const sqlstr = `CALL CaresoftDB.spSucursalEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDSucursal); err != nil {
		return logerror(err)
	}
	return nil
}
