package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpTipoServicioCrear calls the stored procedure 'CaresoftDB.spTipoServicioCrear(varchar)' on db.
func SpTipoServicioCrear(ctx context.Context, db DB, pNombre string) error {
	// call CaresoftDB.spTipoServicioCrear
	const sqlstr = `CALL CaresoftDB.spTipoServicioCrear(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pNombre); err != nil {
		return logerror(err)
	}
	return nil
}
