package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSalaCrear calls the stored procedure 'CaresoftDB.spSalaCrear(enum('d','o'))' on db.
func SpSalaCrear(ctx context.Context, db DB, pEstado EnumDO) error {
	// call CaresoftDB.spSalaCrear
	const sqlstr = `CALL CaresoftDB.spSalaCrear(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pEstado); err != nil {
		return logerror(err)
	}
	return nil
}
