package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpSalaListar calls the stored procedure 'CaresoftDB.spSalaListar()' on db.
func SpSalaListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spSalaListar
	const sqlstr = `CALL CaresoftDB.spSalaListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
