package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAutorizacionActualizar calls the stored procedure 'CaresoftDB.spAutorizacionActualizar(int, int, decimal)' on db.
func SpAutorizacionActualizar(ctx context.Context, db DB, pIDAutorizacion, pIDAseguradora uint, pMontoAsegurado float64) error {
	// call CaresoftDB.spAutorizacionActualizar
	const sqlstr = `CALL CaresoftDB.spAutorizacionActualizar(?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAutorizacion, pIDAseguradora, pMontoAsegurado); err != nil {
		return logerror(err)
	}
	return nil
}
