package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpFacturaEliminar calls the stored procedure 'CaresoftDB.spFacturaEliminar(varchar)' on db.
func SpFacturaEliminar(ctx context.Context, db DB, pFacturaCodigo string) error {
	// call CaresoftDB.spFacturaEliminar
	const sqlstr = `CALL CaresoftDB.spFacturaEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pFacturaCodigo); err != nil {
		return logerror(err)
	}
	return nil
}
