package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpTipoServicioListar calls the stored procedure 'CaresoftDB.spTipoServicioListar()' on db.
func SpTipoServicioListar(ctx context.Context, db DB) error {
	// call CaresoftDB.spTipoServicioListar
	const sqlstr = `CALL CaresoftDB.spTipoServicioListar()`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr); err != nil {
		return logerror(err)
	}
	return nil
}
