package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpProveedorCrear calls the stored procedure 'CaresoftDB.spProveedorCrear(int, varchar, varchar, varchar, varchar)' on db.
func SpProveedorCrear(ctx context.Context, db DB, pRncProveedor uint, pNombre, pDireccion, pTelefono, pCorreo string) error {
	// call CaresoftDB.spProveedorCrear
	const sqlstr = `CALL CaresoftDB.spProveedorCrear(?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pRncProveedor, pNombre, pDireccion, pTelefono, pCorreo); err != nil {
		return logerror(err)
	}
	return nil
}
