package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpReservaEliminar calls the stored procedure 'CaresoftDB.spReservaEliminar(int)' on db.
func SpReservaEliminar(ctx context.Context, db DB, pIDReserva uint) error {
	// call CaresoftDB.spReservaEliminar
	const sqlstr = `CALL CaresoftDB.spReservaEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDReserva); err != nil {
		return logerror(err)
	}
	return nil
}
