package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// SpUsuarioCrearPersonal calls the stored procedure 'CaresoftDB.spUsuarioCrearPersonal(varchar, enum('i','p'), varchar, varchar, enum('m','f'), date, varchar, varchar, varchar, enum('a','c'), varchar, varchar)' on db.
func SpUsuarioCrearPersonal(ctx context.Context, db DB, pDocumento string, pTipoDocumento EnumIP, pNombre, pApellido string, pGenero EnumMF, pFechaNacimiento time.Time, pTelefono, pCorreo, pDireccion string, pRol EnumAC, pUsuarioCodigo, pUsuarioContra string) error {
	// call CaresoftDB.spUsuarioCrearPersonal
	const sqlstr = `CALL CaresoftDB.spUsuarioCrearPersonal(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pDocumento, pTipoDocumento, pNombre, pApellido, pGenero, pFechaNacimiento, pTelefono, pCorreo, pDireccion, pRol, pUsuarioCodigo, pUsuarioContra); err != nil {
		return logerror(err)
	}
	return nil
}
