package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpAutorizacionListar calls the stored procedure 'CaresoftDB.spAutorizacionListar(int)' on db.
func SpAutorizacionListar(ctx context.Context, db DB, pIDAseguradora uint) error {
	// call CaresoftDB.spAutorizacionListar
	const sqlstr = `CALL CaresoftDB.spAutorizacionListar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDAseguradora); err != nil {
		return logerror(err)
	}
	return nil
}
