package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpPagoCrear calls the stored procedure 'CaresoftDB.spPagoCrear(int, decimal)' on db.
func SpPagoCrear(ctx context.Context, db DB, pIDCuenta uint, pMontoPagado float64) error {
	// call CaresoftDB.spPagoCrear
	const sqlstr = `CALL CaresoftDB.spPagoCrear(?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDCuenta, pMontoPagado); err != nil {
		return logerror(err)
	}
	return nil
}
