package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpConsultaInsertarAfeccion calls the stored procedure 'CaresoftDB.spConsultaInsertarAfeccion(varchar, int)' on db.
func SpConsultaInsertarAfeccion(ctx context.Context, db DB, pConsultaCodigo string, pIDAfeccion uint) error {
	// call CaresoftDB.spConsultaInsertarAfeccion
	const sqlstr = `CALL CaresoftDB.spConsultaInsertarAfeccion(?, ?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pConsultaCodigo, pIDAfeccion); err != nil {
		return logerror(err)
	}
	return nil
}
