package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// SpIngresoEliminar calls the stored procedure 'CaresoftDB.spIngresoEliminar(int)' on db.
func SpIngresoEliminar(ctx context.Context, db DB, pIDIngreso uint) error {
	// call CaresoftDB.spIngresoEliminar
	const sqlstr = `CALL CaresoftDB.spIngresoEliminar(?)`
	// run
	logf(sqlstr)
	if _, err := db.ExecContext(ctx, sqlstr, pIDIngreso); err != nil {
		return logerror(err)
	}
	return nil
}
